=== Registries

==== Registry Formats

`GET /\{instance}/registry.json`

*Permission action:* `view-registry`

Returns the list of artifacts formats available in a registry.

===== Path Parameters

[cols="{tbl-pathparams-cols-specs}"]
|===
|Name|Description|Type|Example

|`instance`
|Name of Fatbuildr instance
|_string_
| `prod` or `default`
|===

===== Responses

[cols="{tbl-responses-cols-specs}"]
|===
|Code|Description|Content Type|Data Type

|200
|Operation successful
|`application/json`
|_array[string]_

|403
|Forbidden
|`application/json`
|_xref:#object-error[] object_

|404
|Instance or JWT signing key not found
|`application/json`
|_xref:#object-error[] object_
|===

.Examples
[%collapsible]
====
Request:

[source,shell]
----
$ curl -X GET http://localhost:5000/default/registry.json
----

Response:

[source,json]
----
["rpm","deb"]
----
====

==== Format Distributions

`GET /\{instance}/registry/\{format}.json`

*Permission action:* `view-registry`

Returns the list of available distributions in a registry for a given format.

===== Path Parameters

[cols="{tbl-pathparams-cols-specs}"]
|===
|Name|Description|Type|Example

|`instance`
|Name of Fatbuildr instance
|_string_
| `prod` or `default`

|`format`
|Artifact format name
|_string_
|`deb` or `rpm`
|===

===== Responses

[cols="{tbl-responses-cols-specs}"]
|===
|Code|Description|Content Type|Data Type

|200
|Operation successful
|`application/json`
|_array[string]_

|403
|Forbidden
|`application/json`
|_xref:#object-error[] object_

|404
|Instance, JWT signing key not found or format not supported by the instance
|`application/json`
|_xref:#object-error[] object_
|===

.Examples
[%collapsible]
====
Request:

[source,shell]
----
$ curl -X GET http://localhost:5000/default/registry/rpm.json
----

Response:

[source,json]
----
["el8"]
----
====

==== Distribution Derivatives

`GET /\{instance}/registry/\{format}/\{distribution}.json`

*Permission action:* `view-registry`

Returns the list of derivatives available for the distribution.

===== Path Parameters

[cols="{tbl-pathparams-cols-specs}"]
|===
|Name|Description|Type|Example

|`instance`
|Name of Fatbuildr instance
|_string_
| `prod` or `default`

|`format`
|Artifact format name
|_string_
|`deb` or `rpm`

|`distribution`
|Distribution name
|_string_
|`bullseye` or `el8`
|===

===== Responses

[cols="{tbl-responses-cols-specs}"]
|===
|Code|Description|Content Type|Data Type

|200
|Operation successful
|`application/json`
|_array[string]_

|403
|Forbidden
|`application/json`
|_xref:#object-error[] object_

|404
|Instance, JWT signing key not found, format not supported by the instance or
distribution not found in registry.
|`application/json`
|_xref:#object-error[] object_
|===

.Examples
[%collapsible]
====
Request:

[source,shell]
----
$ curl -X GET http://localhost:5000/default/registry/deb/bullseye.json
----

Response:

[source,json]
----
[
  "main",
  "foox"
]
----
====

==== Derivative Artifacts

`GET /\{instance}/registry/\{format}/\{distribution}/\{derivative}.json`

*Permission action:* `view-registry`

Returns the list of artifacts in a distribution derivative.

===== Path Parameters

[cols="{tbl-pathparams-cols-specs}"]
|===
|Name|Description|Type|Example

|`instance`
|Name of Fatbuildr instance
|_string_
| `prod` or `default`

|`format`
|Artifact format name
|_string_
|`deb` or `rpm`

|`distribution`
|Distribution name
|_string_
|`bullseye` or `el8`

|`derivative`
|Name of distribution derivative
|_string_
|`main`
|===

===== Responses

[cols="{tbl-responses-cols-specs}"]
|===
|Code|Description|Content Type|Data Type

|200
|Operation successful
|`application/json`
|_array[xref:#object-artifact[] object]_

|403
|Forbidden
|`application/json`
|_xref:#object-error[] object_

|404
|Instance, JWT signing key not found, format not supported by the instance,
distribution or derivative not found in registry.
|`application/json`
|_xref:#object-error[] object_
|===

.Examples
[%collapsible]
====
Request:

[source,shell]
----
$ curl -X GET http://localhost:5000/default/registry/deb/bullseye/main.json
----

Response:

[source,json]
----
[
  {
    "architecture": "noarch",
    "name": "fatbuildr",
    "version": "0.1-1.deb11"
  },
  {
    "architecture": "noarch",
    "name": "fatbuildr-common",
    "version": "0.1-1.deb11"
  },
  {
    "architecture": "x86_64",
    "name": "fatbuildr-wrappers",
    "version": "0.1-1.deb11"
  },
  {
    "architecture": "x86_64",
    "name": "fatbuildr-wrappers-dbgsym",
    "version": "0.1-1.deb11"
  },
  {
    "architecture": "src",
    "name": "fatbuildr",
    "version": "0.1-1.deb11"
  }
]
----
====

==== Artifact Information

`GET /\{instance}/registry/\{format}/\{distribution}/\{derivative}/\{architecture}/\{artifact}.json`

*Permission action:* `view-registry`

Returns full description of an artifact in registry.

===== Path Parameters

[cols="{tbl-pathparams-cols-specs}"]
|===
|Name|Description|Type|Example

|`instance`
|Name of Fatbuildr instance
|_string_
| `prod` or `default`

|`format`
|Artifact format name
|_string_
|`deb` or `rpm`

|`distribution`
|Dis$tribution name
|_string_
|`bullseye` or `el8`

|`derivative`
|Name of distribution derivative
|_string_
|`main`

|`architecture`
|Name of CPU architecture of the artifact. The special value `src` refers to
source artifact used as input to produce binary artifacts. The special value
`noarch` refers to architecture independant artifacts.
|_string_
|`x86_64`, `src` or `noarch`

|`artifact`
|Name of the artifact
|_string_
|`fatbuildr`
|===

===== Responses

[cols="{tbl-responses-cols-specs}"]
|===
|Code|Description|Content Type|Data Type

|200
|Operation successful
|`application/json`
|_xref:#object-artifact-desc[]_

|403
|Forbidden
|`application/json`
|_xref:#object-error[] object_

|404
|Instance, JWT signing key not found, format not supported by the instance,
distribution, derivative, architecture or artifact not found in registry.
|`application/json`
|_xref:#object-error[] object_
|===

.Examples
[%collapsible]
====
Request:

[source,shell]
----
$ curl -X GET http://localhost:5000/default/registry/deb/bullseye/main/src/fatbuildr.json
----

Response:

[source,json]
----
{
  "artifact": "fatbuildr",
  "binaries": [
    {
      "architecture": "noarch",
      "name": "fatbuildr",
      "version": "0.1-2.deb11"
    },
    {
      "architecture": "noarch",
      "name": "fatbuildr-common",
      "version": "0.1-2.deb11"
    },
    {
      "architecture": "x86_64",
      "name": "fatbuildr-wrappers",
      "version": "0.1-2.deb11"
    },
    {
      "architecture": "x86_64",
      "name": "fatbuildr-wrappers-dbgsym",
      "version": "0.1-2.deb11"
    }
  ],
  "changelog": [
    {
      "author": "John Doe <john@doe.org>",
      "changes": [
        "Another Fatbuildr test build"
      ],
      "date": 1655841969,
      "version": "0.1-2.deb11"
    },
    {
      "author": "John Doe <john@doe.org>",
      "changes": [
        "Fatbuildr test build"
      ],
      "date": 1655838256,
      "version": "0.1-1.deb11"
    }
  ]
}
----

Request:

[source,shell]
----
$ curl -X GET http://localhost:5000/default/registry/deb/bullseye/main/x86_64/fatbuildr-wrappers.json
----

Response:

[source,json]
----
{
  "artifact": "fatbuildr-wrappers",
  "changelog": [
    {
      "author": "John Doe <john@doe.org>",
      "changes": [
        "Another Fatbuildr test build"
      ],
      "date": 1655841969,
      "version": "0.1-2.deb11"
    },
    {
      "author": "John Doe <john@doe.org>",
      "changes": [
        "Fatbuildr test build"
      ],
      "date": 1655838256,
      "version": "0.1-1.deb11"
    }
  ],
  "source": {
    "architecture": "src",
    "name": "fatbuildr",
    "version": "0.1-2.deb11"
  }
}
----
====


==== Artifact Deletion

`DELETE /\{instance}/registry/\{format}/\{distribution}/\{derivative}/\{architecture}/\{artifact}.json`

*Permission action:* `edit-registry`

Delete an artifact from registry.

===== Path Parameters

[cols="{tbl-pathparams-cols-specs}"]
|===
|Name|Description|Type|Example

|`instance`
|Name of Fatbuildr instance
|_string_
| `prod` or `default`

|`format`
|Artifact format name
|_string_
|`deb` or `rpm`

|`distribution`
|Dis$tribution name
|_string_
|`bullseye` or `el8`

|`derivative`
|Name of distribution derivative
|_string_
|`main`

|`architecture`
|Name of CPU architecture of the artifact. The special value `src` refers to
source artifact used as input to produce binary artifacts. The special value
`noarch` refers to architecture independant artifacts.
|_string_
|`x86_64`, `src` or `noarch`

|`artifact`
|Name of the artifact
|_string_
|`fatbuildr`
|===

===== Query Parameters

[cols="{tbl-queryparams-cols-specs}"]
|===
|Name|Description|Type|Required|Example

|`version`
|Version of the artifact.
|_string_
|✅
| `1.2.3-1`
|===

===== Responses

[cols="{tbl-responses-cols-specs}"]
|===
|Code|Description|Content Type|Data Type

|200
|Operation successful
|`application/json`
|_xref:#object-submitted-task[]_

|403
|Forbidden
|`application/json`
|_xref:#object-error[] object_

|404
|Instance, JWT signing key not found, format not supported by the instance,
distribution, derivative, architecture or artifact not found in registry.
|`application/json`
|_xref:#object-error[] object_
|===

.Examples
[%collapsible]
====
Request:

[source,shell]
----
$ curl -X DELETE http://localhost:5000/default/registry/deb/bullseye/main/src/fatbuildr.json?version=2.0.1
----

Response:

[source,json]
----
{
  "task": "ef6176ad-9489-449a-804e-77370fee2540"
}
----
====

==== Artifact Search

`GET /\{instance}/search.json`

*Permission action:* `view-registry`

Search for artifacts in instance registries.

===== Path Parameters

[cols="{tbl-pathparams-cols-specs}"]
|===
|Name|Description|Type|Example

|`instance`
|Name of Fatbuildr instance
|_string_
| `prod` or `default`
|===

===== Query Parameters

[cols="{tbl-queryparams-cols-specs}"]
|===
|Name|Description|Type|Required|Example

|`artifact`
|Part of artifact name to search. All artifacts whose name contains this
parameter are selected in results.
|_string_
|✓
|`fatbuildr`
|===

===== Responses

[cols="{tbl-responses-cols-specs}"]
|===
|Code|Description|Content Type|Data Type

|200
|Operation successful
|`application/json`
|_xref:#object-artifact-search-result[]_

|400
|Missing _artifact_ query parameter
|`text/html`
|

|403
|Forbidden
|`application/json`
|_xref:#object-error[] object_

|404
|Instance or JWT signing key not found
|`application/json`
|_xref:#object-error[] object_
|===

.Examples
[%collapsible]
====
Request:

[source,shell]
----
$ curl -X GET http://localhost:5000/default/search.json?artifact=fatbuildr
----

Response:

[source,json]
----
{
  "deb": {
    "bullseye": {
      "main": [
        {
          "architecture": "noarch",
          "name": "fatbuildr",
          "version": "0.1-1.deb11"
        },
        {
          "architecture": "noarch",
          "name": "fatbuildr-common",
          "version": "0.1-1.deb11"
        },
        {
          "architecture": "x86_64",
          "name": "fatbuildr-wrappers",
          "version": "0.1-1.deb11"
        },
        {
          "architecture": "x86_64",
          "name": "fatbuildr-wrappers-dbgsym",
          "version": "0.1-1.deb11"
        },
        {
          "architecture": "src",
          "name": "fatbuildr",
          "version": "0.1-1.deb11"
        }
      ]
    }
  },
  "rpm": {
    "el8": {
      "main": [
        {
          "architecture": "noarch",
          "name": "fatbuildr",
          "version": "0.1-1.el8"
        },
        {
          "architecture": "noarch",
          "name": "fatbuildr-common",
          "version": "0.1-1.el8"
        },
        {
          "architecture": "x86_64",
          "name": "fatbuildr-wrappers",
          "version": "0.1-1.el8"
        },
        {
          "architecture": "x86_64",
          "name": "fatbuildr-wrappers-dbgsym",
          "version": "0.1-1.el8"
        },
        {
          "architecture": "src",
          "name": "fatbuildr",
          "version": "0.1-1.el8"
        }
      ]
    }
  }
}
----
====
