#!/bin/bash
# invoke shell if build fails.

FATBUILDR_INTERACTIVE="${FATBUILDR_INTERACTIVE:-no}"

# do nothing if not explicitely interactive
if [[ "${FATBUILDR_INTERACTIVE}" != "yes" ]]; then
  exit 0
fi

BUILDDIR="${BUILDDIR:-/tmp/buildd}"

apt-get install -y "${APTGETOPT[@]}" vim less
cd "$BUILDDIR"/*/debian/..

/bin/bash < /dev/tty > /dev/tty 2> /dev/tty
