ifeval::["{backend}" != "manpage"]
= `fatbuildrctl` command
:reftext: `fatbuildrctl`

This section explains all `fatbuildrctl` command available options, with
many examples and descriptions of its behaviours. The content of the page is
also available in `fatbuildrctl(1)` manpage after installation.

endif::[]

== Synopsis

*fatbuildrctl* [_GENERAL OPTIONS_] COMMAND [_COMMAND OPTIONS_]

== General Options

*-h, --help*::
  Show this help message and exit.

*-v, --version*::
  Show Fatbuildr version number and exit.

*--debug*::
  Enable debug mode with more messages in output.

*--fulldebug*::
  Enable debug mode in external libraries used by Fatbuildr. You should
  probably not need this option, as it is designed for Fatbuildr developers.

*--preferences*=_PREFERENCES_::
  Path to user preference file (default: `~/.config/fatbuildr.ini`). Please
  refer to <<man-pref,*PREFERENCES FILE*>> section for details about this file.

*--uri*=_URI_::
  URI of Fatbuildr server (default: `dbus://system/default` or
  <<env,`$FATBUILDR_URI` environment variable>> if defined). Accepted schemes
  are `dbus`, when interacting with local `fatbuildrd` service on D-Bus, or
  `http(s)` when interacting with potentially remote `fatbuildrweb` proxy (ex:
  `http://build.host/prod`).
+
NOTE: When connecting to `fatbuildrweb` started in mono-instance mode, the URI
does not contain the `fatbuildrd` instance name. In this case, the URI can be as
simple as `http://build.host`.

== Commands

All commands accept *-h, --help* option to get details about available option
for this particular command (_ex:_ `fatbuildrctl images --help`). Commands are
listed in lexicographical order.

*build*::

  Submit artifact build tasks.
+
--
This command accepts the following options:

*-a, --artifact*=_ARTIFACT_::
  Artifact to build.

*-d, --distribution*=_DISTRIBUTION_::
  Targeted distribution name for the built artifact. The format of the
  resulting artifact is deduced from this distribution, based on instance
  pipelines definitions.

*-f, --format*=_FORMAT_::
  Format of the resulting artifact. This is an alternative way to specify the
  targeted distribution. It can be used when only one distribution is declared
  for the given format in instance pipelines definitions. When multiple
  distributions are declared for the given format, the command fails with an
  error. When both *-f, --format* and *-d, --distribution* are specified but
  distribution format and the given format do not match, the command also fails
  with an error.

*--derivative*=_DERIVATIVE_::
  Name of distribution derivative (default: _main_)

*-b, --basedir*=_BASEDIR_::
  Artifacts definitions base directory. The _BASEDIR_ is used in combination
  with _SUBDIR_ to define location of artifact definition. This parameter is
  required unless it is defined in user preferences files (see
  <<man-pref,*PREFERENCES FILE*>> for more details).

*-s, --subdir*=_SUBDIR_::
  Artifact definition subdirectory. Eventually, `fatbuildrctl` searches for the
  artifact definition under the path composed by _BASEDIR_ concatenated with
  _SUBDIR_. By default, _SUBDIR_ is the artifact name.

*--sources*=_[SOURCE_ID#][SOURCE_VERSION@]SOURCE_DIR_::
  Generate artifact source using the source code in a local _SOURCE_DIR_
  directory instead of using the source tarball from the URL declared in
  artifact definition. See <<man-src,*LOCAL SOURCES*>> section for more details.

*--include-git-untracked*::
  Include in artifact source archive generated from local source directory files
  that are untracked in git repository. This option only has effect with
  *--sources* option. See <<man-src,*LOCAL SOURCES*>> section for more details.

*-n, --name*=_NAME_::
  User name for artifact build changelog entry. This option is required, unless
  the user name is defined in user preferences file (see
  <<man-pref,*PREFERENCES FILE*>> for more details).

*-e, --email*=_EMAIL_::
  User email for artifact build changelog entry. This option is required, unless
  the user email is defined in user preferences file (see
  <<man-pref,*PREFERENCES FILE*>> for more details).

*-m, --msg*=_MSG_::
  Build message to set in artifact build changelog entry. This option is
  required, unless a default build message is defined in user preferences file
  (see <<man-pref,*PREFERENCES FILE*>> for more details).

*--batch*::
  Submit task in background.

*-i, --interactive*::
  Submit build in interactive mode. In this mode, users drop into an interactive
  shell inside the build environment in case of build failure. By launching
  commands in this interactive shell, users can more easily diagnose the cause
  of the build issue and eventually find solution. When this option is used,
  `--batch` option is ignored. This mode is available only when the Fatbuildr
  server is accessed locally on D-Bus.

NOTE: *-n, --name*, *-e, --email* and *-m, --msg* options are not actually used
for _osi_ format artifacts as this format does not contain changelogs.

*Examples:*

`$ fatbuildrctl build --artifact foo --distribution bar`::
  Submit task to build artifact _foo_ for distribution _bar_ (using _main_
  default derivative). The format of the artifact is deduced from the
  distribution, based on instance pipelines definitions. The base directory,
  the default build message, the user name and email must be defined in user
  preferences file. The artifact definition must be present in `foo/`
  subdirectory of the base directory.

`$ fatbuildrctl build --artifact foo --format rpm`::
  Submit task to build artifact _foo_ to RPM format. The distribution is
  deduced from the format. This works when only one distribution is declared
  for the rpm format in instance pipelines definitions.

`$ fatbuildrctl build --artifact foo --distribution bar --msg 'build foo for bar'`::
  Submit task to build artifact _foo_ for distribution _bar_ with given message
  in artifact changelog. The base directory, the user name and email must be
  defined in user preferences file.

`$ fatbuildrctl build --artifact foo --distribution bar --basedir ~/path/to/basedir --subdir pkg`::
  Submit task to build artifact _foo_ for distribution _bar_ using artifact
  definition located in `pkg/` subdirectory of `~/path/to/basedir` directory.
  The default build message, the user name and email must be defined in user
  preferences file.

`$ fatbuildrctl build --artifact foo --distribution bar --derivative baz`::
  Submit task to build artifact _foo_ for derivative _baz_ of distribution
  _bar_. The _baz_ derivate must be declared in instance pipelines definitions
  and `artifact.yml` file of artifact definition directory.

`$ fatbuildrctl build --artifact foo --distribution bar --batch`::
  Submit task to build artifact _foo_ for distribution _bar_ in background.

`$ fatbuildrctl build --artifact foo --distribution bar --interactive`::
  Submit task to build artifact _foo_ for distribution _bar_, then wait for the
  build task to start and print its output until it is over. Launch an
  interactive shell in the build environment in case of build failure.

`$ fatbuildrctl build --artifact foo --distribution bar --sources 1.2.3@~/path/to/sources`::
  Generate source tarball of artifact _foo_ with files located in directory
  `~/path/to/sources` tagged with version _1.2.3_, then submit task to build
  this artifact for distribution _bar_.
--

*history*::

  Manage tasks history.
+
--
This command accepts the following subcommands:

*list*::
  List last 10 terminated tasks in history with all their parameters. This is
  the default subcommand.

*purge*::
  Submit task to purge tasks history with their workspaces according to the
  policy defined on server side.

The command accepts the following options:

*--batch*::
  Submit task in background.

*Examples:*

`$ fatbuildrctl history`::
`$ fatbuildrctl history list`::
  List last 10 terminated tasks in history with all their parameters.

`$ fatbuildrctl history purge`::
  Submit task to purge tasks history with their workspaces according to the
  policy defined on server side.

`$ fatbuildrctl history purge --batch`::
  Submit task to purge tasks history in background.
--
*images*::

  Manage container images and build environments. One operation among the 
  available subcommands must be specified.
+
--
The *images* subcommand accepts the following subcommands:

*create*:::
  Submit tasks to create container images. Unless *-f, --format* filter
  is used, all images for all formats declared in instance pipelines are
  created. One task per image (or format) is submitted on server side.
+
The *create* subcommand accepts the following options:

*-f, --format*=_FORMAT_::
  Create container image specific to format _FORMAT_.

*--force*::
  Force creation of container images even if already existing. Without this
  option, creating container image that already exists gives an error.

*--batch*::
  Submit task in background.

*update*:::
  Submit tasks to update OS packages of container images. Unless *-f, --format*
  filter is used, all images for all formats declared in instance pipelines are
  updated. One task per image is submitted on server side.
+
The *update* subcommand accepts the following options:

*-f, --format*=_FORMAT_::
  Update container image specific to format _FORMAT_.

*--batch*::
  Submit task in background.

*shell*:::
  Submit a task to launch an interactive shell or execute a command as root in a
  container image. Unless only one format is declared in the instance pipelines,
  it is necessary to select the image with *-f, --format* filter. The task is
  terminated when the shell is exited.
+
The *shell* subcommand accepts the following options:

*-f, --format*=_FORMAT_::
  Select container image specific to format _FORMAT_.

*command*::
  Command to execute in container image. Without this option, an interative
  shell is launched.

*command*::
  Command to execute in container image. Without this option, an interative
  shell is launched.

*env-create*:::
  Submit tasks to create the build environments in the container images. Unless
  *-f, --format*, *-d, --distribution* or *-a, --architecture* filters are used,
  all build environments for all formats and architectures declared in instance
  pipelines are created. One task per build environment is submitted on server
  side.
+
The *env-create* subcommand accepts the following options:

*-f, --format*=_FORMAT_::
  Create build environments for format _FORMAT_.

*-d, --distribution*=_DISTRIBUTION_::
  Create build environments for distribution _DISTRIBUTION_.

*-a, --architecture*=_ARCHITECTURE_::
  Create build environments for the hardware architecture _ARCHITECTURE_.

*--batch*::
  Submit task in background.

*env-update*:::
  Submit tasks to update the build environments in the container images. Unless
  *-f, --format*, *-d, --distribution* or *-a, --architecture* filters are used,
  all build environments for all formats and architectures declared in instance
  pipelines are updated. One task per build environment is submitted on server
  side.
+
The *env-update* subcommand accepts the following options:

*-f, --format*=_FORMAT_::
  Update build environments for format _FORMAT_.

*-d, --distribution*=_DISTRIBUTION_::
  Update build environments for distribution _DISTRIBUTION_.

*-a, --architecture*=_ARCHITECTURE_::
  Update build environments for the hardware architecture _ARCHITECTURE_.

*--batch*::
  Submit task in background.

*env-shell*:::
  Submit a task to launch an interactive shell or execute command as root in a
  build environment. The build environment must be selected with *-f, --format*,
  *-d, --distribution* and *-a, --architecture* filters. The task is terminated
  when the shell is exited.
+
The *env-shell* subcommand accepts the following options:

*-f, --format*=_FORMAT_::
  Select build environment for format _FORMAT_.

*-d, --distribution*=_DISTRIBUTION_::
  Select build environment for distribution _DISTRIBUTION_.

*-a, --architecture*=_ARCHITECTURE_::
  Select build environment for the hardware architecture _ARCHITECTURE_.

*command*::
  Command to execute in build environment. Without this option, an interative
  shell is launched.

*Examples:*

`$ fatbuildrctl images create`::
  Submit tasks to create container images for all formats declared in instance
  pipelines.

`$ fatbuildrctl images update --format rpm --batch`::
  Submit tasks to update container image for RPM format in background.

`$ fatbuildrctl images shell --format rpm`::
  Submit tasks to open an interactive shell in an instance of a container
  running the image for RPM format.

`$ fatbuildrctl images shell --format deb \-- dpkg -l`::
  Submit tasks to execute `dpkg -l` command in an instance of a container
  running the image for Deb format.

`$ fatbuildrctl images env-create --format deb --batch`::
  Submit tasks to create all build environments declared in instance pipelines
  for Deb format in background.

`$ fatbuildrctl images env-update --distribution el8`::
  Submit tasks to update the build environments declared in instances pipelines
  for the _el8_ distribution, for all supported architectures.

`$ fatbuildrctl images env-update --distribution sid --architecture x86_64`::
  Submit a task to update the build environments declared in instances pipelines
  for the _sid_ distribution for `x86_64` hardware architecture only.

`$ fatbuildrctl images env-shell --distribution el8 --architecture arm64`::
  Submit a task to open an interactive shell in the build environment declared
  in instances pipelines for the _el8_ distribution for `arm64` hardware
  architecture.

`$ fatbuildrctl images env-shell --distribution sid \-- apt show curl`::
  Submit a task to execute command `apt show curl` in the build environment
  declared in instances pipelines for the _sid_ distribution.
--

*keyring*::

  Manage keyring.
+
--
NOTE: The keyrings managed by Fatbuildr are created with a masterkey and a
signing subkey. This subkey is actually used to sign the artifacts and
registries. The masterkey is only used to sign the subkey.

NOTE: The keyring keys are encrypted on disks using a randomly generated
passphrase. Fatbuildr users and administrators are not expected to know or
manipulate this passphrase, it is managed transparently by Fatbuildr.

This command accepts the following subcommands:

*show*::
  Print the keyring information including its subject, format, size,
  fingerprint, expiration, etc. This is the default subcommand.

*export*::
  Print keyring public key in armoured format.

*create*::
  Submit keyring creation task. The key is created using the parameters defined
  in Fatbuildr server configuration file. If the keyring already exists, it is
  overwritten.

*renew*::
  Submit keyring renewal task. The new key expiry date is set using
  *--duration* option.

The *renew* subcommand accepts the following options:

*--duration*=_DURATION_::
  The validity duration of the renewed keyring. The duration accepts the
  following time units: _w_ for weeks, _m_ for months, _y_ for years. The
  default unit is a number of days. The special value 0 indicates no
  expirary date. This option is required with *renew* subcommand. It is
  silently ignored with other subcommands.

*--batch*::
  Submit task in background.

*Examples:*

`$ fatbuildrctl keyring`::
`$ fatbuildrctl keyring show`::
  Print keyring information, or report an error if the keyring does not exist.

`$ fatbuildrctl keyring export`::
  Print keyring public key in armoured format.

`$ fatbuildrctl keyring create`::
  Submit task to create the keyring.

`$ fatbuildrctl keyring renew --duration 10`::
  Submit task to set keyring expiry in 10 days from now.

`$ fatbuildrctl keyring renew --duration 2y`::
  Submit task to set keyring expiry in 2 years from now.

`$ fatbuildrctl keyring renew --duration 0`::
  Submit task to remove keyring expiry.
--

*list*::

  List currently running and pending tasks with their parameters. This commands
  does not accept any option.

*patches*::

  Manage artifact patch queue. This downloads artifact source code tarball,
  selecting the version intended for the given derivative. Then, it creates a
  temporary Git repository initialized with artifact source code in initial
  commit and existing artifact patches into successive commits. After the Git
  repository is initialized, a subshell is launched into it. You can then
  modify existing patches by editing commit history, or add additional patches
  with new commits. When the subshell is exited, the commit log is exported
  into a set of patches for the artifact, and the temporary Git repository is
  destroyed.
+
--
NOTE: The downloaded source code tarball is saved in user cache directory. If
environment variable `$XDG_CACHE_HOME` is defined, it is honoured. Otherwise,
the default user cache directory `~/.cache` is selected. Fatbuildr creates a
dedicated `fatbuildr` subdirectory in this user cache directory where all source
code tarballs are placed. If the downloaded source code tarball is already
present in cache, it is used directly and additional download is avoided.

This command accepts the following options:

*-a, --artifact*=_ARTIFACT_::
  Edit _ARTIFACT_ patch queue.

*--derivative*=_DERIVATIVE_::
  Select artifact source version intended for _DERIVATIVE_ (default: _main_).

*-b, --basedir*=_BASEDIR_::
  Artifacts definitions base directory. The _BASEDIR_ is used in combination
  with _SUBDIR_ to define location of artifact definition. This parameter is
  required unless it is defined in user preferences files (see
  <<man-pref,*PREFERENCES FILE*>> for more details).

*-s, --subdir*=_SUBDIR_::
  Artifact definition subdirectory. Eventually, `fatbuildrctl` searches for the
  artifact definition under the path composed by _BASEDIR_ concatenated with
  _SUBDIR_. By default, _SUBDIR_ is the artifact name.

*--sources*=_[SOURCE_ID#][SOURCE_VERSION@]SOURCE_DIR_::
  Generate artifact source using the source code in a local _SOURCE_DIR_
  directory instead of using the source tarball from the URL declared in
  artifact definition. See <<man-src,*LOCAL SOURCES*>> section for more details.

*--include-git-untracked*::
  Include in artifact source archive generated from local source directory files
  that are untracked in git repository.  This option only has effect with
  *--sources* option. See <<man-src,*LOCAL SOURCES*>> section for more details.

*-n, --name*=_NAME_::
  User name for temporary Git repository initial commit author and commiter.
  This option is required, unless the user name is defined in user preferences
  file (see <<man-pref,*PREFERENCES FILE*>> for more details).

*-e, --email*=_EMAIL_::
  User email for temporary Git repository initial commit author and commiter.
  This option is required, unless the user email is defined in user preferences
  file (see <<man-pref,*PREFERENCES FILE*>> for more details).

*Examples:*

`$ fatbuildrctl patches --artifact foo`::
  Edit patch queue of artifact _foo_ (using version intended _main_ default
  derivative). The base directory, the default build message, the user name and
  email must be defined in user preferences file. The artifact definition must
  be present in `foo/` subdirectory of the base directory.

`$ fatbuildrctl patches --artifact foo --derivative bar`::
  Edit patch queue of artifact _foo_ using version intended for _bar_
  derivative.

`$ fatbuildrctl patches --artifact foo --basedir ~/path/to/basedir --subdir pkg`::
  Edit patch queue of artifact _foo_ using artifact definition located in `pkg/`
  subdirectory of `~/path/to/basedir` directory.

`$ fatbuildrctl patches --artifact foo --name 'John Doe' --email john@doe.org`::
  Edit patch queue of artifact _foo_. This initial commit of temporary Git
  repository will created using `John Doe <john@doe.org>` identity as author and
  commiter.

`$ fatbuildrctl patches --artifact foo --sources 1.2.3@~/path/to/sources`::
  Edit patch queue of artifact _foo_ based on a generated source tarball with
  files located in directory `~/path/to/sources` tagged with version _1.2.3_.
--

*registry*::

  Query and manage artifacts in registries.
+
--
This command accepts the following subcommands:

*list*::
  List artifacts matching given filters.

*delete*::
  Remove artifacts matching given filters from registry.

The command accepts the following options:

*-d, --distribution*=_DISTRIBUTION_::
  Registry distribution name. This parameter is required. The format of the
  artifact is deduced from the distribution, based on instance pipelines
  definitions.

*--derivative*=_DERIVATIVE_::
  Registry distribution derivative name (default: _main_).

*-a, --artifact*=_ARTIFACT_::
  Part of artifact name. All artifacts whose name contains _ARTIFACT_ are
  selected. By default, all artifacts are selected.

*Examples:*

`$ fatbuildrctl registry --distribution foo`::
`$ fatbuildrctl registry --distribution foo list`::
  List all artifacts found in distribution _foo_ (in _main_ default derivative).

`$ fatbuildrctl registry --distribution foo --derivative bar`::
  List all artifacts found in _bar_ derivative of distribution _foo_.

`$ fatbuildrctl registry --distribution foo --artifact baz`::
  List all artifacts whose in name contains _baz_ in distribution _foo_.

`$ fatbuildrctl registry --distribution foo --artifact baz delete`::
  Remove all artifacts whose in name contains _baz_ from distribution _foo_ (in
  _main_ default derivative).
--

*tokens*::

  Manage tokens for authentication to HTTP REST API. See <<tokens,*API TOKENS*> >
  section for more details.
+
--
This command accepts the following subcommands:

*list*::
  Print the list of JWT tokens available in the tokens directory defined in the
  user preferences file with all their details (path, associated URI, expiration
  date, etc). See <<man-pref,*PREFERENCES FILE*>> section for more details. This
  is the default subcommand.

*generate*::
  Generate a token. This subcommand only works for local instance through DBus
  interface.

*save*::
  Reads a token on standard input and saves it to a local file. The *--uri*
  option is required to determine the file name. The file is saved in the
  tokens directory defined in the user's preferences file. See <<man-pref,
  *PREFERENCES FILE*>> section for more details.

The command accepts the following options:

*--uri*=_URI_::
  The URI associated to the save token. This parameter is required when using
  the *save* subcommand, it is ignored otherwise.

*Examples:*

`$ fatbuildrctl tokens`::
`$ fatbuildrctl tokens list`::
  Print the list of JWT tokens available in the tokens directory.

`$ fatbuildrctl tokens generate`::
  Generates a JWT token for remote authentification on the local instance. The
  token is printed on standard output.

`$ fatbuildrctl tokens save --uri https://build.server`::
  Reads a token on standard input and saves it to a local file associated to the
  given remote instance URI.
--

*watch*::

  Get output of running and archived tasks.
+
--
This command accepts the following argument:

*TASK*::
  Get output of task _TASK_. By default, currently running task is selected.
  When the selected task is running, its output is streamed until its end. If
  _TASK_ is not found in pending, running and archived tasks, an error is
  reported. If the argument is not given and no task is currently running, an
  error is also reported. If _TASK_ is pending, the command waits for the task
  to start.

*Examples:*

`$ fatbuildrctl watch`::
  Get output of currently running task until its end.

`$ fatbuildrctl watch a97737c0-5ecd-41d7-ba3a-ed46e03a2eb0`::
  Get output of task a97737c0-5ecd-41d7-ba3a-ed46e03a2eb0.
--

[[man-src]]
== Local Sources

Some `fatbuildrctl` commands (`build`, `patches`) provide the possibility to
generate an artifact source tarball with the content of a local source tree
using *--sources* option.

The value of this option has the following format:
*[SOURCE_ID#][SOURCE_VERSION@]SOURCE_DIR [[SOURCE_ID#][SOURCE_VERSION@]SOURCE_DIR]*

The local directory which contains the source tree is specified with
_SOURCE_DIR_.

By default, the ID associated to the source is the artifact name. It is
considered by Fatbuildr as the main source for the artifact. For artifact with
multiple sources, it is possible to generate a tarball for a supplementary
source by specifying _SOURCE_ID_ followed by _#_. Specifying a _SOURCE_ID_ not
declared as a supplementary source in xref:repo.adoc#def[artifact definition
file] results in an error.

By default, the version number declared for this source in artifact definition
file is used in generated tarball filename. It is possible to prefix the source
directory with an alternate version _SOURCE_VERSION_ followed by _@_.

The **--sources** option accepts multiple values for artifact defined with
multiple sources. An error is reported when a source ID is specified more than
once.

*Examples:*

`fatbuildrctl […] --sources ~/path/to/code`::
  Generate archive for artifact main source with the content of directory
  `~/path/to/code` (using the version number defined in artifact definition
  file).

`fatbuildrctl […] --sources 1.2.3@~/path/to/code`::
  Generate archive for artifact main source with the content of directory
  `~/path/to/code` and version `1.2.3`.

`fatbuildrctl […] --sources other#~/path/to/other-code`::
  Generate archive for artifact _other_ source with the content of directory
  `~/path/to/other-code` (using the version number defined for other source in
  artifact definition file).

`fatbuildrctl […] --sources other#4.5.6@~/path/to/other-code`::
  Generate archive for artifact _other_ source with the content of directory
  `~/path/to/other-code` and version `4.5.6`.

`fatbuildrctl […] --sources 1.2.3@~/path/to/code other#4.5.6@~/path/to/other-code`::
  Generate archive for artifact main source with the content of directory
  `~/path/to/code` and version `1.2.3`, and generate archive for artifact
  _other_ source with the content of directory `~/path/to/other-code` and
  version `4.5.6`.

Some files are automatically excluded by Fatbuildr from the generated archives:

* All files whose name start by `.git` (_ex:_ `.gitignore` and `.git/` folder),
* The `debian/` subdirectory recursively,
* If the source tree is an initialized Git repository, all files referenced as
  untracked in this repository (typically in `.gitignore`). This can be disabled
  with **--include-git-untracked** option.

[[man-pref]]
== Preferences file

To avoid specifying some options to `fatbuildrctl`, it is possible to define a
preferences file with some defaults user settings.

The path to this file can be provided to `fatbuildrctl` using
*--preferences*=_PREFERENCES_ general option. By default, `fatbuildrctl` checks
if `$XDG_CONFIG_HOME` environment variable is defined with an existing directory
and search for a file named `fatbuildr.ini` inside this directory. If the
environment variable is not defined, `fatbuildrctl` tries to load file
`~/.config/fatbuildrctl.ini`.

The preferences file is formatted as an INI file. It can contains two sections:

*[user]*::

  This section can contain the following parameters:
+
--
*name*::
  User real name. When defined, it is used as default value for
  *-n, --name*=_NAME_ option of *build* and *patches* commands.

*email*::
  User emame. When defined, it is used as default value for
  *-e, --email*=_EMAIL_ option of *build* and *patches* commands.
--

*[prefs]*::

  This section can contain the following parameters:
+
--
*uri*::
  URI of Fatbuildr instance. When defined, it is used as default value for
  *--uri*=_URI_ general option.

*basedir*::
  Path to artifact definition repository. When defined, it is used as default
  value for *-b, --basedir*=_BASEDIR_ option of *build* and *patches*
  commands.

*message*::
  Default build message. When defined, it is used as default value for
  *-m, --msg*=_MSG_ option of *build* command.

*tokens*::
  The path to the directory where `fatbuildrctl` saves and load JWT tokens for
  remote authentication to the REST API. The default value is
  `~/.local/share/fatbuildr` or `$XDG_DATA_HOME/fatbuildr` if the environment
  variable is defined.

*commit_template*::
  The path to the git commit message template file used to preformat the
  messages of new git commits when using `fatbuildrctl patches` command. Default
  value is [.path]#`/usr/share/fatbuildr/commit-message-template`#.
--

This is a full example of a user preferences file:

[source,ini]
----
[user]
name = John Doe
email = joe@doe.com

[prefs]
uri = http://build.host/dev
basedir = /home/john/path/to/basedir
message = Artifact maintenance build
----

[#env]
== Environment Variables

To avoid specifying some options to `fatbuildrctl`, it is possible to define the
following environment variables:

*FATBUILDR_URI*::
  When defined, this environment variable overrides the instance URI defined in
  <<man-pref,user preferences file>>. When *--uri* option is set, this
  environment variable is ignored.

[#tokens]
== API Tokens

Authentication to Fatbuildr xref:api.adoc[REST API] is realized with JSON WEB
Tokens (JWT). Depending on the xref:admin:web.adoc#policy[policy], users must
have a valid token prior to calling some API endpoints. To obtain a valid token,
users can run this command:

[source,console]
----
$ fatbuildrctl tokens generate
<secret personal token>
----

This command requests fatbuildrd daemon to generate and sign a valid token for
the current user. The token provided by the server is printed on standard
output.

The *tokens generate* command only works with local Fatbuildr instance through
DBus interface. For remote authentication, users are expected to connect to the
remote host (eg. with SSH) to generate the token and provide it to the
*tokens save* command to save it on the client host. For example:

[source,console]
----
$ ssh john@build.server fatbuildrctl --uri dbus://system/default tokens generate | \
  fatbuildrctl tokens save --uri https://build.server/default
token saved in file /home/john/.local/share/fatbuildr/aHR0cHM6Ly9idWlsZC5zZXJ2ZXIvZGVmYXVsdA==.token
----

This command generates a token on _default_ instance of _build.server_ remote
host for user _john_ and saves this token in a file associated to the URI of
this remote instance, in local _john_ tokens directory.

The path to this tokens directory is defined in user's preference file. See
<<man-pref, *PREFERENCES FILE*>> section for more details. The filename of the
token is the URI of the associated remote instance encoded in base64 and the
_.token_ extension. This naming convention notably guarantees uniqueness of
token files for each remote instance.

All tokens available locally can be listed with this command:

[source,console]
----
$ fatbuildrctl tokens
token:
  path: /home/john/.local/share/fatbuildr/aHR0cHM6Ly9idWlsZC5zZXJ2ZXIvZGVmYXVsdA==.token
  uri: https://build.server/default
  user: john
  issued at: 1970-01-01T00:00:00
  expiration: 2099-12-31T23:59:59
  audience: fatbuildr
----

When a token associated to a remote instance is available locally, it is
automatically loaded and sent by *fatbuildrctl* for authentication to this
instance.

== Exit status

*0*::
  `fatbuildrctl` has processed command with success.

*1*::
  `fatbuildrctl` encountered an error.
