= Installation Guide

== Setup host

NOTE: This installation guide is designed for Debian 11 _« bullseye »_ host. It
will be ported to other OS later, notably when Fatbuildr is able to build Deb and
RPM packages for various distributions.

As _root_, enable _backports_ repository by creating file
`/etc/apt/sources.list.d/backports.list` with this content:

----
deb http://deb.debian.org/debian bullseye-backports main contrib non-free
----

Install required packages:

[source,bash]
----
apt install systemd-container vim curl qemu-system-x86 dnf rpm python3-yaml python3-jinja2 python3-gpg
----

Install _osi_ from _backports_:

[source,bash]
----
apt install -t bullseye-backports mkosi
----

As a workaround for https://github.com/systemd/mkosi/issues/864[mkosi #864 issue],
download Fedora GPG keys and deploy them at the location expected by `mkosi`:

[source,bash]
----
mkdir /etc/pki/rpm-gpg && \
curl https://getfedora.org/static/fedora.gpg \
  -o /etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-35-x86_64
----

Start and enable `systemd-{resolved,networkd}` services to easily setup
containers networking and DNS:

[source,bash]
----
systemctl start systemd-resolved.service
systemctl enable systemd-resolved.service
systemctl start systemd-networkd.service
systemctl enable systemd-networkd.service
----

Create cache directory:

[source,bash]
----
mkdir /var/cache/fatbuildr
----

Create keyring directory:

[source,bash]
----
mkdir --mode=0700 /var/lib/fatbuildr/keyring
----

Generate GPG signing key:

[source,bash]
----
bin/init-key
----

== Base images

To build the base images, run the following command:

[source,bash]
----
sudo bin/build-images.sh
----

== Test builds

=== RPM

----
sudo /usr/sbin/usermod -a -G mock $USER
mock --root=rocky-8-x86_64 --buildsrpm --sources=. --spec=slurm-21.08.4/slurm.spec
cp /var/lib/mock/rocky-8-x86_64/result/slurm-21.08.4-1.el8.src.rpm .
mock --root=rocky-8-x86_64 --rebuild slurm-21.08.4-1.el8.src.rpm --with mysql
----

Mock doc: https://rpm-software-management.github.io/mock/

=== Deb

----
dget http://deb.debian.org/debian/pool/main/s/slurm-wlm/slurm-wlm_20.11.8-1.dsc
cowbuilder --build slurm-wlm_20.11.8-1.dsc
----
