#!/usr/bin/python3
#
# Copyright (C) 2024 Rackslab
#
# This file is part of Fatbuildr.
#
# Fatbuildr is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Fatbuildr is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Fatbuildr.  If not, see <https://www.gnu.org/licenses/>.

"""Example generic tasks hook for Fatbuildr to send message in syslog."""

import syslog
import os


def main():
    if os.environ["FATBUILDR_TASK_STAGE"] == "start":
        syslog.syslog(
            f"fatbuildr-hook task {os.environ['FATBUILDR_TASK_ID']}@"
            f"{os.environ['FATBUILDR_INSTANCE_ID']} is starting"
        )
    else:
        syslog.syslog(
            f"fatbuildr-hook task {os.environ['FATBUILDR_TASK_ID']}@"
            f"{os.environ['FATBUILDR_INSTANCE_ID']} is terminated: "
            f"{os.environ['FATBUILDR_TASK_RESULT']}"
        )


if __name__ == "__main__":
    main()
