= Fatbuildrweb

Fatbuildrweb component is automatically installed with Fatbuildr, there is
nothing more to install. However, it is not started by default. There are 2
supported ways to start the service:

* In autonomous mode, where the application starts with its built-in HTTP server
* As WSGI application integrated with an existing HTTP server

The autonomous mode is easy and straightforward to setup but it is not
recommended for large setup with many users. The WSGI mode benefits from the
better performances and scalability offered by advanced HTTP servers such as
Apache2 and nginx.

[#autonomous]
== Autonomous Service

Start _fatbuildrweb_ service with this command as root (or sudo):

[source,shell]
----
# systemctl start fatbuildrweb.service
----

The service is available at this URL: http://localhost:5000/

Please refer to the _Administration Guide_ to
xref:admin:web.adoc#interface[configure an alternative listening interface and
TCP port].

To automatically start the service on system start, enable the service with this
command:

[source,shell]
----
# systemctl enable fatbuildrweb.service
----

[#wsgi]
== WSGI Application

Setting up a WSGI application depends on the HTTP server and the WSGI module.
The following subsections provides installation instructions for some
combinations of those.

NOTE: If you need help to setup Fatbuildrweb as a WSGI application with a
different combination of HTTP server and WSGI module, please
https://github.com/rackslab/fatbuildr/issues/new[open an issue]. If you want to
contribute documentation for an additional HTTP server or WSGI module, please
https://github.com/rackslab/fatbuildr/compare[open a pull request]!

=== Apache2 and `mod_wsgi`

Install Apache2 HTTP service with WSGI module:

* On Debian/Ubuntu:
+
[source,shell]
----
# apt install apache2 libapache2-mod-wsgi-py3
# a2enmod wsgi  # The module must be enabled manually.
----

* On RHEL:
+
[source,shell]
----
# dnf install httpd python3-mod_wsgi
# systemctl enable httpd.service  # and enabled manually.
----

Add the following lines in the most appropriate `VirtualHost` of your Apache2
configuration:

[source]
----
WSGIDaemonProcess fatbuildrweb-all user=fatbuildr group=fatbuildr locale=en_US.UTF-8
WSGIScriptAlias / /usr/share/fatbuildr/wsgi/fatbuildrweb.wsgi
WSGIPassAuthorization On

<Directory /usr/share/fatbuildr/wsgi>
  WSGIProcessGroup fatbuildrweb-all
  WSGIApplicationGroup %{GLOBAL}
  Require all granted
</Directory>
----

Finally, restart the service to enable modifications:

* On Debian/Ubuntu:
+
[source,shell]
----
# systemctl restart apache2.service
----

* On RHEL:
+
[source,shell]
----
# systemctl restart httpd.service
----

At this stage, Fatbuildrweb is available to the root path of your `VirtualHost`.

NOTE: With the Apache2 configuration snippet provided, Fatbuildrweb application
is started in _multi-instances mode_. Find out
xref:admin:web.adoc#monoinstance[_mono-instance mode_ configuration
instructions] to change this setting.
