#!/bin/bash
# Add distribution and possible derivatives repositories with ascending
# priorities.

echo "Repository: ${FATBUILDR_REPO}"
echo "Derivatives: ${FATBUILDR_DERIVATIVES}"

if [ ! -d "${FATBUILDR_REPO}" ] ; then
    echo "Unable to find repository directory ${FATBUILDR_REPO}, exiting."
    exit 0
elif [ ! -f "${FATBUILDR_REPO}/dists/${DISTRIBUTION}/Release" ]; then
    echo "Release file for distribution ${DISTRIBUTION} in directory ${FATBUILDR_REPO} not found, exiting."
    exit 0
else
    # add entry in sources list
    echo "deb [signed-by=${FATBUILDR_KEYRING}] file://${FATBUILDR_REPO} ${DISTRIBUTION} ${FATBUILDR_DERIVATIVES}" >> /etc/apt/sources.list

    # setup ascending priority to derivatives
    PRIORITY=1000
    for DERIVATIVE in ${FATBUILDR_DERIVATIVES}; do
        cat <<EOF >>/etc/apt/preferences.d/90fatbuildr
Package: *
Pin: release o=${FATBUILDR_SOURCE},c=${DERIVATIVE}
Pin-Priority: ${PRIORITY}

EOF
        PRIORITY=$(($PRIORITY+1000))
    done

    # update package cache
    apt-get update
fi
